### ISSUE TITLE
Missing access token

### ISSUE THREAD

**Issue by tamaracks** [aaronpk/OwnYourSwarm#16]
OwnYourSwarm is finding my checkins, but can't get them to my micropub endpoint, because it's missing an access token.

I may have skipped over a request for a token in the browser while setting it up, although I'm not sure. But I can't find any way to add a token now. I can sign out and sign back in, but there's no prompt for a token this time.

**Comment by aaronpk** [comment]
OwnYourSwarm obtains an access token during the login flow. It shouldn't actually be possible to log in without OwnYourSwarm getting an access token as a result.

I checked the logs and I do see that it has an access token for your site.

OwnYourSwarm will always send a JSON request, which some Micropub endpoints don't support. The docs for what it sends are here: https://ownyourswarm.p3k.io/docs If you're using the Wordpress Micropub plugin for example, I don't think that one supports JSON requests yet.

**Comment by tamaracks** [comment]
Hmm. That's too bad. I'd love to get checkins integrated into my blog.

But why does the information returned to me in the browser show this?

```
HTTP/1.1 401 Unauthorized
Date: Mon, 01 May 2017 23:52:32 GMT
Server: Apache
Link: <https://tokens.indieauth.com/token>; rel="token_endpoint", <https://www.darkglass.org/wp-json/webmention/1.0/endpoint>; rel="webmention", <https://www.darkglass.org/wp-json/webmention/1.0/endpoint>; rel="http://webmention.org/"
Content-Type: application/json; charset=UTF-8
Vary: Accept-Encoding
Transfer-Encoding: chunked

"missing access token"
```

Or is that just an artifact of the JSON not being accepted?

**Comment by tamaracks** [comment]
FWIW, the developer of the plugin says that the current version of the plugin does support JSON. He requested that I put an issue in that project, which I've done. https://github.com/snarfed/wordpress-micropub/issues/56 if you're curious.

**Comment by tamaracks** [comment]
Closing this, because the missing token issue is on the receiving side.
