### ISSUE TITLE
Provide event data to the endpoint

### ISSUE THREAD

**Issue by tamaracks** [aaronpk/OwnYourSwarm#18]
I noticed that for one of my checkins, the associated event data was found in the Swarm object, but isn't put into the h-entry object. It would be great if that could be added somewhere.

**Comment by aaronpk** [comment]
Great idea! I'm not quite sure the best way to do this. I think this will require some more Microformats brainstorming around how to represent these checkins at a place *and* event.

**Comment by tamaracks** [comment]
It would be cool if you could include it in the content for starters, but I can understand why you might be reluctant to do that. 

Events have long been a source of irritation to me because 4sq/Swarm doesn't seem to share it anywhere themselves other than in their own app. It doesn't show up on Facebook or Twitter when you share a checkin from the Swarm app. It doesn't show up in the .ics calendar feeds they supply. Grr! So I was really excited to see that it's part of the data you retrieve in OwnYourSwarm. So close!

I don't think you use the event data on your own web site (or do you?) but I did notice you show the coins. I am curious how you do that. Is it because you take the Swam object in its entirety and process it without using a micropub  endpoint? Or can an endpoint be configured to take that data somehow?

**Comment by aaronpk** [comment]
I'd definitely be up for including it in the `content` text for the "simple" POST requests. I don't know how I would map it to a Microformats post yet, so it wouldn't be in the JSON post for now.

The Swarm coins are actually sent as Webmentions after the post is created via Micropub! It looks like OwnYourSwarm is getting a `400` response with `Pings are disabled for this post` from your Webmention endpoint. If you enable Webmentions on your checkin posts, you'll start to see those right now!

**Comment by tamaracks** [comment]
Thanks for checking that. I did not know it was responding like that. I think I had something a setting incorrectly checked (didn't realize it applied to the webmention plugin). I believe I've corrected it now.

It will remain to be seen if that's true and what the Wordpress webmention/webmention comments plugins actually do with that data. :)

**Comment by aaronpk** [comment]
You'll probably miss the coin number, but you'll get the text Swarm sends. I'm not sure how to provide fallback behavior in that case. Maybe if you're using the "simple" Micropub format, you should also get "simple" Webmentions? (the coin number would be included in the text of the comment)

**Comment by tamaracks** [comment]
Maybe. I'm afraid that I don't have a handle on the different varieties/modes of these interactions yet. :)

**Comment by aaronpk** [comment]
I had to look for quite a while to find one of my checkins with event info to test with!

You should be receiving the event info in checkins now! The text of the post will look like

> Checked in at Laurelhurst Theater & Pub for Whiskey Tango Foxtrot

**Comment by tamaracks** [comment]
Thanks!

**Comment by tamaracks** [comment]
I did get the webmentions on later checkins. But you were right, no coins. Just each of the little blurb lines Swarm gives you. Fallback behavior would be nice on that. Should that be a different issue?

**Comment by aaronpk** [comment]
Great! Yep, I already opened a new issue for that: #20

**Comment by tamaracks** [comment]
@aaronpk I've checked into a few events since the last update, and I haven't gotten any additions to my post text. Any ideas?

**Comment by aaronpk** [comment]
@tamaracks strange, could you provide a link to one of your event checkins? I can take a look at the Swarm API data for it to see what's going on.

**Comment by tamaracks** [comment]
https://www.swarmapp.com/tamaracks/checkin/593896355ba0464bed23e588

I think that's the URL you mean, but if not, let me know!

**Comment by aaronpk** [comment]
Ah, I thought your site was set up to receive "simple" requests from OwnYourSwarm, but it looks like you're set to receive JSON posts. I haven't added events to JSON posts yet since we haven't settled on what the Microformats representation of a checkin to an event looks like yet.

**Comment by aaronpk** [comment]
If you switch your account to send the "simple" posts, the event info is included in the "content" of the checkin along with the venue name and your text. I'm going to close this issue and open a new one for event data in JSON requests.

**Comment by tamaracks** [comment]
Thanks for checking into that. I'm not quite up on all the terminology yet, so I didn't make that connection. I guess my hesitation about using the simple checkin is that I am currently getting the location info imported into metadata in WP. Presumably because the WordPress micropub server is capable of processing that data somehow. I assume that if I switch OYS to sending simple data, then it wouldn't be sending the location data in JSON either. Is that correct? Or did I assume wrongly?

**Comment by aaronpk** [comment]
It still sends the geo data separately, but I can't remember whether the wordpress plugin handles it, although I think it does. @snarfed might be able to shine some light on this! The one thing you will definitely lose switching to simple format is the venue name isn't hyperlinked to the venue URL.

I do want to solve event data in the JSON requests soon anyway, so if you don't mind missing that data for a while longer you could wait for that.

**Comment by snarfed** [comment]
the wordpress micropub plugin supports both simple (form-encoded) and JSON for pretty much all properties, including location (as address properties, `latitude` and `longitude`, and `geo:` URIs).

**Comment by aaronpk** [comment]
Great! Then you shouldn't lose the location info as WP metadata if you switch to the simple format.
