### ISSUE TITLE
Checkin created by other person should be updated after you check yourself in

### ISSUE THREAD

**Issue by sebsel** [aaronpk/OwnYourSwarm#24]
Seems like when someone else checks me in (like you did [here](https://seblog.nl/2017/06/17/15)), the post is created on my site. If I then check myself in, adding a text and a photo, Swarm upgrades your checkin of me to add the details of my own checkin.

But, on my site, it seems like the photo got through (probably the photo polling) but the text did not.

I don't have logs for Micropub requests, unfortunately, so I can't check if it tried.

**Comment by aaronpk** [comment]
this just happened to me as well! I think the current implementation only looks for new photos when it sends updates.
