### ISSUE TITLE
Something is going wrong with time stamps when endpoint is WordPress 

### ISSUE THREAD

**Issue by dougbeal** [aaronpk/OwnYourSwarm#27]
I will investigate and figure out where the problem lies

**Comment by dougbeal** [comment]
https://dougbeal.com/2017/06/23/509/#commentsd
https://ownyourswarm.p3k.io/checkin/594dc5b25a2c916a34193afc/50c0ba0a22b78562c51d09ec7512c0a9 2017-06-24 01:51:46	2017-06-24 01:55:00
Swarm says:
2017-06-24 at 1:51 am	(Edit)
Your first Tapas Restaurant.

via ownyourswarm.p3k.io

**Comment by aaronpk** [comment]
:sigh: timezones. Looks like Wordpress is converting this and displaying it in UTC rather than in the local timezone. I'm not sure where in the Wordpress flow that's happening, but OwnYourSwarm sends the timestamp in the local time with the timezone offset. (`2017-06-23T18:51:46-07:00`)

**Comment by dshanske** [comment]
I resolved this in the Micropub plugin in October. It's in the GitHub version

**Comment by dshanske** [comment]
Suggest you close

**Comment by gloriouslyawkwardlife** [comment]
@dshanske Coming back to 2025, the plug-in is posting in Standard Time when the WordPress site is set to ‘America/New_York’ and it’s DST.

**Comment by dshanske** [comment]
I wonder if it's on the WordPress or other side.. I know I did some work on this in micropub for WordPress
