### ISSUE TITLE
[Feature Request]Can we include the info of who checks us in?

### ISSUE THREAD

**Issue by jonnybarnes** [aaronpk/OwnYourSwarm#29]
Currently the `createdBy` info of the Swarm Checkin object isn’t included in the `h-entry` checkin object that’s sent to the µpub endpoint.

**Comment by sebsel** [comment]
I think I talked about this with @aaronpk before, and we were wondering how to display that on our own website.

Back then, Swarm indicated it by adding the photo of the person who checked you in to your own photo. In the new app design, they added a textual representation of this too.

![img_9198](https://user-images.githubusercontent.com/16517999/29242364-4c484342-7f8c-11e7-9cd4-4f7f20f089d4.PNG)

I am still in doubt how and if I want to display this info. Also a question to think about: how do you want to represent this in Microformats?

**Comment by jonnybarnes** [comment]
`<span class="p-checked-in-by h-card">`?

Also, just because ownyourswarm provides the information doesn’t mean everyone has to display it on their own site?

**Comment by jonnybarnes** [comment]
Had a shat with Zegnat on #microformats, and maybe if someone else makes a swarm checkin and tags you in it

OwnYourSwarm should markup the other person as the author of the checkin.

**Comment by Zegnat** [comment]
Summing up my points from the chat, note that I have no stake in the game as I do not use Swarm.

I would expect whoever did the actual checking in on Swarm to be listed as the author on the `h-entry` submitted to the Micropub endpoint. People they are checking in to be added as [person tags](https://indieweb.org/person-tag).

If Alice checks in Bob on Swarm, and Bob is using OwnYourSwarm, I would expect Bob to get something like:

```json
{
    "type": [
        "h-entry"
    ],
    "properties": {
        "author": [
            {
                "type": [
                    "h-card"
                ],
                "properties": {
                    "name": [
                        "Alice"
                    ],
                    "url": [
                        "https://alice.example.com/"
                    ]
                },
                "value": "https://alice.example.com/"
            }
        ],
        "category": [
            {
                "type": [
                    "h-card"
                ],
                "properties": {
                    "name": [
                        "Bob"
                    ],
                    "url": [
                        "https://bob.example.com/"
                    ]
                },
                "value": "https://bob.example.com/"
            }
        ],
        "name": [
            "Checked in at Eve\u2019s Restaurant"
        ],
        "location": [
            "Eve\u2019s Restaurant"
        ]
    }
}
```

Note that this only works when Alice and Bob are at <i>Eve’s Restaurant</i> together. @jonnybarnes tells me this is always the case on Swarm.

**Comment by jonnybarnes** [comment]
Could do with a second opinion on being together. I’ve only ever checked someone else in, or been checked in by someone else, on Swarm when we are both thier togther.

Does anyone know if that is *always* the case with Swarm?

**Comment by sebsel** [comment]
For the second opinion: yes, I believe, on Swarm, it is impossible to make a checkin for someone else, without checking in yourself too. The posting interface does not allow it.

Creating a post with a different author almost sounds more like a webmention to the homepage / representative h-card, with a `u-category h-card` / person-tag.

If a micropub endpoint of a user does not support a different author, but does support tagging persons (like mine, at the moment, but I think no-one supports displaying a different author at the moment), in that case the post will show up as the author tagged himself (instead of the person he's with), which is a strange fallback.
Because of that, a homepage mention makes more sense. Then people can pick that up as a [person tag](https://indieweb.org/person-tag) if they like.

An argument against the webmention is, that on Swarm, the person is actually checked in. A post is created on their profile / timeline. That sounds as micropub again.

(It's a bit of a complicated matter. Just adding a few pro's and cons here.)

**Comment by aaronpk** [comment]
I'm a little concerned that there's so much mf2 being discussed without first thinking about the design of it.

I don't like the idea of having a different author of the checkin for two reasons:

1) On Swarm, the checkin still looks like it's created by the person who is checked in, and has an additional line saying "checked in by"

2) Micropub endpoints usually don't support multi author posts right now, and I think there are quite a lot of other implications of accepting posts with alternate authors. Things like how is the alternate author verified? Can anyone be listed as an alternate author, or is it limited to a list?

**Comment by aaronpk** [comment]
Yes this seems different from a home page webmention of tagging someone in a post. That's more like posting on someone's Facebook wall.

Are there other silos that support other people creating posts on your own account? 

The thing that's interesting about the Swarm case is that other than the "checked in by" text, the post is a native post on the person's account, much more than just tagging someone.

**Comment by jonnybarnes** [comment]
So would the easiest way to include the data be to add an extra checked-in-by property to the submitted microformat data?

Or is the best thing not to submit the data at all?

**Comment by aaronpk** [comment]
It appears Swarm still shows a small photo of the person who checked you in, as well as adds the line "checked in by" below the checkin.

![checkin](https://media.aaronpk.com/Screen-Shot-2017-12-25-08-00-51-SqPTzk9FdN.jpg)

**Comment by aaronpk** [comment]
I'm leaning towards `u-checked-in-by h-card` since it really does feel like a normal post other than this additional property. 

This will show up as a new Micropub JSON property like this:

```json
        "checked-in-by": [
            {
                "type": [
                    "h-card"
                ],
                "properties": {
                    "url": [
                        "http://anomalily.net/",
                        "https://foursquare.com/user/894076"
                    ],
                    "name": [
                        "anomalily"
                    ],
                    "photo": [
                        "https://igx.4sqi.net/img/user/300x300/894076-UEP315CWOZJNKG2J.jpg"
                    ]
                },
                "value": "http://anomalily.net/"
            }
        ]
```

OwnYourSwarm doesn't render HTML for checkins, but if it did, the HTML would be:

```html
Checked in by <a href="http://anomalily.net/" class="u-checked-in-by h-card"><img src="https://igx.4sqi.net/img/user/300x300/894076-UEP315CWOZJNKG2J.jpg"> anomalily</a>
```

**Comment by dshanske** [comment]
This works for me
