### ISSUE TITLE
[bug] My latest checkin isn't hitting my servers endpoint 

### ISSUE THREAD

**Issue by EdwardHinkle** [aaronpk/OwnYourSwarm#33]
I haven't had issues with any other checkins. From what I can tell my endpoint is never being hit by OwnYourSwarm in my logs. The only thing I can tell that's different in my most recent checkin is that I added a hashtag (#nanowrimo17) I don't know if the # is somehow messing up ownyourswarm and it's breaking before getting pushed to my server?

The "Preview" button does show the h-entry:
```
{
    "type": [
        "h-entry"
    ],
    "properties": {
        "published": [
            "2017-10-12T21:18:16-04:00"
        ],
        "syndication": [
            "https://www.swarmapp.com/user/12192241/checkin/59e014583b83072f78b903a0"
        ],
        "content": [
            "Researching our books for NaNoWriMo #nanowrimo17 @ash"
        ],
        "checkin": [
            {
                "type": [
                    "h-card"
                ],
                "properties": {
                    "name": [
                        "Starbucks"
                    ],
                    "url": [
                        "https://foursquare.com/v/5421a3fb498e5af295e7c96d",
                        "http://www.starbucks.com",
                        "https://twitter.com/starbucks"
                    ],
                    "tel": [
                        "(301) 874-6017"
                    ],
                    "latitude": [
                        39.325787553009
                    ],
                    "longitude": [
                        -77.349690408015
                    ],
                    "street-address": [
                        "3410 Urbana Pike"
                    ],
                    "locality": [
                        "Urbana"
                    ],
                    "region": [
                        "MD"
                    ],
                    "country-name": [
                        "United States"
                    ],
                    "postal-code": [
                        "21704"
                    ]
                }
            }
        ]
    }
}
```

**Comment by aaronpk** [comment]
How long has it been since you checked in? Sometimes Foursquare doesn't run the web hook, so there's a separate feature of OYS that polls your checkins to find missed ones.

Does the "Import" button do anything? Try clicking "reset" and then "import".

**Comment by EdwardHinkle** [comment]
Last successful checkin was two days ago. I did the reset and import and I didn't see a ping on my micropub endpoint

**Comment by EdwardHinkle** [comment]
So it turns out I think ownyourswarm might be down. I’ve checked in other places and haven’t received any new checkin posts. I also glanced at your site and the last checkin on your site is from yesterday morning: https://aaronparecki.com/2017/10/12/15/
You might not have checked in anywhere else then but I’m guessing you have. Lol

No worries. I know you are out of town but I just thought I’d follow up with more info

**Comment by aaronpk** [comment]
well that's weird! the queue processor just stopped getting new jobs. there's 94 jobs waiting to be processed! I'm also a little confused why the cron job didn't pick up on that and fill in the missing gaps.

**Comment by aaronpk** [comment]
ah the cron job only runs twice a day. I'm going to bump that up to every 4 hours.

**Comment by aaronpk** [comment]
Restarted the workers and it's running through the backlog now. I have no idea what happened! You should have a bunch of post requests in your logs now. Looks like they're getting rejected saying "Missing h value". Your account is set to "json" mode which doesn't include that parameter since it sends a full Microformats JSON object as the POST request.

**Comment by EdwardHinkle** [comment]
Haha suddenly I just got a bunch of webmentions from ownyourswarm and I thought, “Aaron must have figured it out for all those guys to appear”. I’ve received the Micropub posts for my missing checkins

**Comment by EdwardHinkle** [comment]
Really? It’s showing as rejected? Odd... they were accepted on my end 🤔

**Comment by aaronpk** [comment]
Hmm, this checkin: [59e13fd84febd50c6775c303](https://www.swarmapp.com/12192241/checkin/59e13fd84febd50c6775c303)? (that URL should work but will look like a 404 error for anyone that isn't your friend on swarm) was one that had an error, tho it looks like it tried it again shortly after and it worked fine. You will probably see a bunch of 400 responses in your logs.
