### ISSUE TITLE
JSON request to Micro.blog

### ISSUE THREAD

**Issue by TheDimPause** [aaronpk/OwnYourSwarm#34]
I've been posting my check-ins as the simple html form-encoded format successfully to my site hosted at Manton Reece's Micro.blog, but when I try the JSON request I get the error:

```
HTTP/1.1 400 Bad Request
Server: nginx/1.6.2
Date: Mon, 13 Nov 2017 12:44:12 GMT
Content-Type: application/json
Content-Length: 70
Connection: keep-alive
Access-Control-Allow-Origin: *
Access-Control-Allow-Credentials: true
X-Content-Type-Options: nosniff

{"error":"invalid_request","error_description":"No content or photo."}
```
I'm afraid I don't  know enough to tell whether this is a problem originating at the OwnYourSwarm end or if it's just that Micro.blog does not support checkins like this. Apologies for raising it here if it's a Micro.blog issue!

**Comment by aaronpk** [comment]
I think Micro.blog only supports the form-encoded format. @manton can correct me if I'm wrong.

**Comment by manton** [comment]
Micro.blog does prefer form-encoded, although it has limited support for JSON requests too. @TheDimPause, any chance you have a copy of the JSON it's sending?

**Comment by TheDimPause** [comment]
Whoops - only just noticed your replies - as I understand it an example of the JSON sent would be the h-entry Checkin Object

```
{
    "type": [
        "h-entry"
    ],
    "properties": {
        "published": [
            "2017-12-03T13:35:43+00:00"
        ],
        "syndication": [
            "https://www.swarmapp.com/user/76497711/checkin/5a23fdafdec1d62dfb40cbec"
        ],
        "content": [
            "Sunday Lunch."
        ],
        "checkin": [
            {
                "type": [
                    "h-card"
                ],
                "properties": {
                    "name": [
                        "Rhoswenallt Inn"
                    ],
                    "url": [
                        "https://foursquare.com/v/4d19df42401db60c206ffda4",
                        "http://www.rhoswenallt.co.uk"
                    ],
                    "tel": [
                        "01685 871055"
                    ],
                    "latitude": [
                        51.722409274249
                    ],
                    "longitude": [
                        -3.428453207016
                    ],
                    "street-address": [
                        "Werfa, Abernant"
                    ],
                    "locality": [
                        "Aberdare"
                    ],
                    "country-name": [
                        "United Kingdom"
                    ],
                    "postal-code": [
                        "CF44 0YS"
                    ]
                }
            }
        ]
    }
}

**Comment by aaronpk** [comment]
Just wanted to bump this to see if micro.blog has support for these JSON requests yet, or whether that's on the roadmap.

**Comment by manton** [comment]
@aaronpk It still ignores the `checkin` part of the JSON, so the post will "work" but be incomplete. Perhaps Micro.blog can append the location's `name` and `url` to the end of the post as a first step.

**Comment by aaronpk** [comment]
Great! If you're ready to support the idea of recognizing check-in posts on Micro.blog that seems like a reasonable approach. If not, I'm happy for the answer for people using micro.blog to be to use form-encoded requests from OYS, since OYS already has some smarts about making a plaintext representation of checkins for form-encoded format.

**Comment by aaronpk** [comment]
I'm going to close this issue since there hasn't been any discussion on it for a while. The best option for micro.blog is to use the "Simple" mode so that the name of the venue you checked in to will be included in the post contents on micro.blog.
