### ISSUE TITLE
Send Property when Checked in by Another

### ISSUE THREAD

**Issue by dshanske** [aaronpk/OwnYourSwarm#35]
If Swarm has who checked you in, pass that along to Micropub.

**Comment by sebsel** [comment]
dub of #29 :)

**Comment by dshanske** [comment]
I was sitting next to @aaronpk when I did this. I figured if someone had suggested it, he'd say so

**Comment by aaronpk** [comment]
Closing as a duplicate of #29, let's continue the discussion there. Sorry I forgot about that thread in Austin!
