### ISSUE TITLE
Differenciate between personal backfeed and swarm coin Webmentions

### ISSUE THREAD

**Issue by sebsel** [aaronpk/OwnYourSwarm#37]
This is in light of the GDPR :)

It would be nice if there was some sort of switch in OwnYourSwarm, that would disable the backfeed of replies and likes done by actual people, as opposed to the webmentions sent to syndicate stickers and coins given out by Swarm itself.

It might be nicer to have the backfeed as opt-in instead of opt-out, don’t know if you agree on that one.

**Comment by aaronpk** [comment]
I'd be happy to add a toggle to disable both kinds of backfeed. I think I will keep them enabled by default for now though.
